Models/SongsViewModel.cs
using MusicApp.Entity;

namespace MusicApp.Models
{
    public class SongsViewModel
    {
        public List<Song> Songs{ get; set; }
    }
}

Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicApp.Identity;

namespace MusicApp.Controllers
{
	[Authorize(Roles = "Admin")] //admin rolünde olmayan kullanicilar bu controller altındaki sayfaya giremesin
	public class RolesController : Controller
	{
		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<AppRole> _roleManager;
		public RolesController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
		{
			_userManager = userManager;
			_roleManager = roleManager;
		}
		public async Task<IActionResult> RoleList()
		{
			var model = await _roleManager.Roles.ToListAsync();
			return View(model);
		}

		//public IActionResult RoleCreate()
		//{
		//	return View();
		//}

		private IEnumerable<AppRole> GetRoles()
		{
			//var model = _roleManager.Roles.Select(r=>new AppRole
			//{
			//	Id=r.Id,
			//	Name=r.Name,
			//}).ToList();
			//return model;

			return _roleManager.Roles.ToList();
		}
		[HttpPost]
		public async Task<IActionResult> RoleCreate(AppRole model)
		{
			if (ModelState.IsValid)
			{
				var result = await _roleManager.CreateAsync(model);

				if (result.Succeeded)
				{
					return RedirectToAction("RoleList");
				}
				foreach (var err in result.Errors) //eger hata/hatalar varsa yazdıralım
				{
					ModelState.AddModelError("", err.Description);
				}
			}
			return View("RoleList",GetRoles());
		}
		[HttpPost]
		public async Task<IActionResult> RoleDelete(string name)
		{
			var role = await _roleManager.FindByNameAsync(name);
			if (role != null)
			{
				await _roleManager.DeleteAsync(role);
			}
			return RedirectToAction("RoleList");
		}

		public async Task<IActionResult> RoleEdit(string id)
		{
			var role = await _roleManager.FindByIdAsync(id);

			if (role != null && role.Name != null)
			{
				ViewBag.Users = await _userManager.GetUsersInRoleAsync(role.Name);
				return View(role);
			}
			return RedirectToAction("RoleList");
		}

		[HttpPost]
		public async Task<IActionResult> RoleEdit(AppRole model)
		{
			if (ModelState.IsValid)
			{
				var role = await _roleManager.FindByIdAsync(model.Id);
				if (role != null)
				{
					role.Name = model.Name;

					var result = await _roleManager.UpdateAsync(role);
					if (result.Succeeded)
					{
						return RedirectToAction("RoleList");
					}
					foreach (IdentityError err in result.Errors)
					{
						ModelState.AddModelError("", err.Description);
					}
					if (role.Name != null)
					{
						ViewBag.Users = await _userManager.GetUsersInRoleAsync(role.Name);
					}
				}
			}
			return View(model);
		}
	}
}

Controllers/SongsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicApp.Data;
using MusicApp.Models;

namespace MusicApp.Controllers
{
	public class SongsController : BaseController
	{
		//private readonly SongContext _context;

		//basecontrollerdan kalıtım aldığımız için contexti injection islemini burada yapmayalım

		public SongsController(SongContext context):base(context) 
		{
			//_context = context;
		}
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult List(int? id)                    //id türleri q ise aranan kelimeyi temsil eder. id kısmında türe göre q kısmında aranan kelimeye göre filtreler
		{
			var songs = _context.Songs.AsQueryable();

			if (id != null)                                             //burası şarkı türüne göre filtreleme yapacak
			{
				songs = songs
					.Include(s => s.Genres)
					.Where(s => s.Genres.Any(g => g.GenreId == id));
			}
			
			var model = new SongsViewModel
			{
				Songs = songs.ToList()
			};

			return View("Songs", model);                                    //bu sekilde yaparsak List.cshtml adında dosya olusturmak yerine Songs.cshtml dosyasına yonlendirebiliriz.
		}
		public IActionResult Searching(string q)
		{
			var songs = _context.Songs.AsQueryable();

			if (!string.IsNullOrEmpty(q))
			{
				songs = songs
					.Include(s=>s.Artists)
					.Where(s=>s.SongName.Contains(q)||
					s.Artists.Any(a=>a.ArtistName.Contains(q)));
			}
			var model = new SongsViewModel
			{
				Songs = songs.ToList() 
			};
			return View("Songs", model);

		}
		public IActionResult Details(int id)
		{
			//var model = _context.Songs.Find(id);

			/*ONEMLİ üstteki satır varken detay sayfamıza artist bilgilerini getiremiyorduk, cünkü many to many ilişki var ve biz bu tabloyu şarkı tablomuza
			dahil etmiyorduk. aşagıdaki gibi include ederek artist bilgilerini alırız ve songs tablosu ile join yaparız artık null olarak gözükmeyecek 
			şarkının artistnamesi var ise detay sayfasında gözükecek.*/
			//aynı şekilde Genres bilgilerini de bu yüzden eklemek zorundayız.

			var model = _context.Songs
				.Include(s => s.Artists)
				.Include(g => g.Genres)
				.FirstOrDefault(s => s.SongId == id);

			//eğer 1 şarkıyı birden fazla sanatçı söylemişse detay kısmında sanatçılar alt alta çıkıyordu, bunu istemedim yan yana olsun istedim. string.Join()
			var artists = model.Artists.Select(a => a.ArtistName).ToList();
			var artistNames = string.Join(", ", artists);
			ViewBag.ArtistNames = artistNames;

			var genres = model.Genres.Select(g => g.GenreName).ToList();
			var genreNames = string.Join("&", genres);
			ViewBag.GenreNames = genreNames;

			var artistNationality = model.Artists.Select(a=>a.Nationality).ToList();

			return View(model);
		}
	}
}

Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicApp.Data;
using MusicApp.Identity;
using MusicApp.IdentityModels;

namespace MusicApp.Controllers
{
	[Authorize(Roles = "Admin")] //admin rolünde olmayan kullanicilar bu controller altındaki sayfaya giremesin mesela member rolündeki veya rolü olmayan kullanicilar giremeyecek
	//onlar program.cste tanimladigimiz AccessDeniedPath = accessdenied olan sayfaya yonlendirilecek
	public class UsersController : Controller
	{
		//Bu Injection islemi de oluyor.
		//private readonly SongContext _context;
		//public UsersController(SongContext context)
		//{
		//	_context = context;
		//}

		private readonly UserManager<AppUser> _userManager;
		private readonly RoleManager<AppRole> _roleManager;

		public UsersController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
		{
			_userManager = userManager;
			_roleManager = roleManager;
		}

		//[Authorize(Roles = "admin")] bunu yukarıda tanımlamak yerine örn sadece burada tanımlarsak sadece bu kısma admin rolündeki kisiler girebilir.
		public IActionResult UserList()
		{
			var model = _userManager.Users;
			return View(model);
		}

		//[AllowAnonymous] //ya da bunu diyerek admine ait olan sayfada sadece ilgili parta giris izni verilebilir.
		public async Task<IActionResult> UserEdit(string id)
		{
			if (id == null) return RedirectToAction("UserList");

			var user = await _userManager.FindByIdAsync(id);

			if (user != null)
			{
				ViewBag.Roles = await _roleManager.Roles.Select(i => i.Name).ToListAsync();
				var model = new EditUserViewModel
				{
					Id = user.Id,
					FullName = user.FullName,
					Email = user.Email,
					SelectedRoles = await _userManager.GetRolesAsync(user)
				};
				return View(model);
			}
			return RedirectToAction("UserList");
		}

		[HttpPost]
		public async Task<IActionResult> UserEdit(string id, EditUserViewModel model)
		{
			if (id != model.Id) return RedirectToAction("UserList");

			ViewBag.Roles = await _roleManager.Roles.Select(i => i.Name).ToListAsync();

			if (ModelState.IsValid)
			{
				var user = await _userManager.FindByIdAsync(model.Id);

				if (user != null)
				{
					user.Email = model.Email;
					user.FullName = model.FullName;

					var result = await _userManager.UpdateAsync(user);
					if (result.Succeeded && !string.IsNullOrEmpty(model.Password))
					{
						await _userManager.RemovePasswordAsync(user);
						await _userManager.AddPasswordAsync(user, model.Password);
					}
					if (result.Succeeded)
					{
						await _userManager.RemoveFromRolesAsync(user, await _userManager.GetRolesAsync(user)); //once userdan rolleri kaldıralım

						if (model.SelectedRoles != null)
						{
							await _userManager.AddToRolesAsync(user, model.SelectedRoles); //sonra usera rolleri atayalım
						}
						return RedirectToAction("UserList");
					}

					foreach (IdentityError err in result.Errors) //useri güncellerken hata alırsak ilgili mesajları yazdıralım
					{
						ModelState.AddModelError("", err.Description);
					}
				}
			}
			return View(model);
		}

		[HttpPost]
		public async Task<IActionResult> UserDelete(string email)
		{
			var user = await _userManager.FindByEmailAsync(email);
			if (user != null)
			{
				var result = await _userManager.DeleteAsync(user);
				if (result.Succeeded)
				{
					return RedirectToAction("UserList");
				}
				foreach (var err in result.Errors)
				{
					ModelState.AddModelError("", err.Description);
				}
			}
			return RedirectToAction("UserList");
		}
	}
}

ViewComponents/GenreDropDownViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MusicApp.Data;

namespace MusicApp.ViewComponents
{
    public class GenreDropDownViewComponent : ViewComponent
    {
        private readonly SongContext _context;

        public GenreDropDownViewComponent(SongContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            //var genreNames =await _context.Genres.Select(g => g.GenreName).ToListAsync();
            var genreNames =await _context.Genres.ToListAsync();
            
            return View(genreNames);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - MusicApp</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/MusicApp.styles.css" asp-append-version="true" />

	<link rel="stylesheet" href="~/css/styles.css" asp-append-version="true">

</head>
<body>
	<header>
		@await Html.PartialAsync("_navbar") @* navbar icin yeni ve bos bir view dosyası olusturmustuk ve onu bu sekilde cagiriyoruz  *@
		@RenderSection("header",false) @*render section araccılığıyla index.cshtml'de yani sadece anasayfada header (jumbotron) olusturduk.*@

		<div class="container mt-4">
			<!-- TempData["message"]'i göstermek için kontrol -->
			@if (TempData["message"] != null)
			{
				<div class="row">
					<div class="col-lg-12">
						<div class="alert alert-warning">
							@TempData["message"]
						</div>
					</div>
				</div>
			}

			<!-- Diğer sayfa içeriği burada yer alır -->
		</div>
		
	</header>
	<div class="container mt-5">
		@*mt-3: genre listesi ve sayfa elemanları biraz asagıda olsun*@
		<main role="main" class="pb-3">
			@if (IsSectionDefined("_genrelist"))
			{
				<div class="row">
					<div class="col-md-2">
						<h2>Genres</h2>
						@RenderSection("_genrelist",false)
					</div>
					<div class="col-md-10">

						@RenderBody()

					</div>
				</div>
			}
			else
			{
				@*eger bir html sayfasında _genrelist adında bir section tanımlanmadıysa mesela anasayfada yok, o zaman _genrelist kısmı olusmasın ve 12 bölmeli olsun, 2ye10luk degil*@
				{
					<div class="row">
						<div class="col-md-12">
							@RenderBody()
						</div>
					</div>
				}
			}
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_genrelist.cshtml
@* liste(kategoriya da menu) ekleyelim, liste icin yeni ve bir view dosyası olusturduk (Partial View)*@

@* @model List<Genre>


<div class="list-group">
	@foreach (var genre in Model)
	{
		<a href="#" class="list-group-item list-group-item-action">@genre.GenreName</a>
	}
</div> *@
@*Bu cshtml hiç kullanılmıyor.*@

Views/Shared/_header.cshtml
@* jumbotron, header kodu (Partial View, razor view empty)*@
	<div class="bg-secondary p-5">
		<div class="container">
			<h1 class="display-4">Başlık</h1> @*web sayfasının amacını bildiren baslık*@
			<p class="lead">Açıklama</p>
		</div>
	</div>

Views/Shared/_navbar.cshtml
@*navbar ekleyelim, navbar icin yeni ve bir view dosyası olusturduk (partial view, razor view empty)*@

<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
		<div class="navbar-brand">Rate The Song</div>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" asp-controller="Songs" asp-action="List">Songs</a>
				</li>
				@if (User.Identity?.IsAuthenticated == true && User.IsInRole("Admin"))
				{

					<li class="nav-item">
						<a class="nav-link" asp-controller="Admin" asp-action="AddSong">Admin Add Song</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Admin" asp-action="SongList">Admin Songs</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Admin" asp-action="GenreList">Admin Genres</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Admin" asp-action="ArtistList">Admin Artists</a>
					</li>
				}

				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						Genres
					</a>
					<ul class="dropdown-menu">

						<li><a class="dropdown-item" href="/Songs/List">All Songs</a></li>
						<li><hr class="dropdown-divider"></li>

						@await Component.InvokeAsync("GenreDropDown")

					</ul>
				</li>
				@*admin rolünde olan kisiler bu linkleri görebilsin, ancak yine de admin olmayanlar ilgili url'ye tıklarsa o sayfaya erişebilir bunun icin Controllerlarda Authorize(Roles="Admin") yazabiliriz. metoduna bak*@
				@if (User.Identity?.IsAuthenticated == true && User.IsInRole("Admin")) //user dogrulanmıssa ve admin rolünde ise
				{
					<li class="nav-item">
						<a class="nav-link" asp-controller="Users" asp-action="UserList">Users</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" asp-controller="Roles" asp-action="RoleList">Roles</a>
					</li>
				}

			</ul>

			<ul class="navbar-nav ms-auto">
				@*saga dogru yanastirdik.*@
				@if (User.Identity?.IsAuthenticated == true) //user e-postasını dogrulayıp kayıt olmussa
				{
					<li class="nav-item">
						<a class="nav-link">Hello @User.Identity.Name</a>
					</li>

					<li>
						<a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
					</li>
				}
				else
				{
					<li class="nav-item">
						<a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
					</li>

					<li class="nav-item">
						<a class="nav-link" asp-controller="Account" asp-action="Register">Register</a>
					</li>
				}

			</ul>

			<form asp-controller="songs" asp-action="searching" class="d-flex" role="search">
				<input class="form-control me-2" name="q" type="search" placeholder="Song & Artist & Band" aria-label="Search">
				<button class="btn btn-outline-success mr-0" type="submit">Search</button>
			</form>
		</div>
	</div>
</nav>

Views/Shared/_song.cshtml
@model Song

<div class="col">
	<a asp-controller="Songs" asp-action="Details" asp-route-id="@Model.SongId" class="card-link">
		<div class="card">
			<img src="/img/@Model.ImageUrl" class="card-img-top" alt="@Model.SongName">
			<div class="card-body">
				<h5 class="card-title">@Model.SongName</h5>
				<div class="description">
					<p class="card-text">
						@{
							@if (Model.Description?.Length > 135) //? koymazsak nullable olarak isaretlemezsek description bilgisi girmedğimizde burası hata verir
							{
								Model.Description = Model.Description.Substring(0, 135) + "...";
							}
						}
						@Model.Description
					</p>
				</div>
			</div>
		</div>
	</a>
</div>
@* <div class="col">
	<div class="card mb-3">
		<div class="row">
			<div class="col-md-4">
				<img src="/img/@Model.ImageUrl" class="img-fluid" alt="@Model.Name">
			</div>
			<div class="col-md-8">
				<div class="card-body">
					<h5 class="card-title">@Model.Name</h5>
					<p class="card-text">@Model.Description This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
					<a></a>
				</div>
			</div>
		</div>
	</div>
</div>  *@